import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { lstat, mkdir, readFile, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import {
  approveSkill,
  archiveAutoGeneratedSkills,
  AUTO_GENERATED_MARKER,
  draftSkill,
  isValidSkillName,
  linkHarnessSkill,
  pinSkill,
  skillDescriptionProblem,
  skillNameFrom,
  skillNameProblem,
  unlinkHarnessSkills,
  updateSkill,
  upsertSkill,
} from "../src/skill-factory.ts";
import { makeWorkspace } from "./helpers.ts";

describe("skill names are class-level, never session titles", () => {
  test("the names the old code produced are all rejected", () => {
    // Every one of these was on disk in ~/.agentik/skills on 2026-09-01.
    const produced = [
      "clo-turer-le-raf-openhermesbot-web-migration-0021-applique-e-age",
      "cre-e-moi-l-us-comple-te-de-taille-e-source-e-plan-de-fini-sur-o",
      "fix-les-erreurs-d-affichage-du-dialog-personnaliser-la-barre-lat",
      "analyse-fix-la-description-d-un-ticket-est-tronque-e-en-mode-e-d",
      "revert-complet-des-sessions-extra-cs-vers-bot-only-migration-002",
      "cre-e-l-us-ohb-18-sur-opentrack-puis-imple-mente-1-4-sse-sans-re",
      "learned-workflow",
    ];
    for (const name of produced) {
      if (name === "learned-workflow") continue; // valid shape; it is the *fallback* that is gone
      expect(skillNameProblem(name)).toBeDefined();
    }
    expect(skillNameProblem("fix-drawer")).toBe("session_prefix");
    expect(skillNameProblem("debug-race-condition")).toBe("session_prefix");
    expect(skillNameProblem("opentrack-ohb-15")).toBe("session_token");
    expect(skillNameProblem("release-2026-09-01")).toBe("session_token");
    expect(skillNameProblem("a".repeat(41))).toBe("too_long");
    expect(skillNameProblem("Export CSV")).toBe("charset");
    expect(skillNameProblem("migration-applique-e")).toBe("cut_mid_word");
  });

  test("class-level names pass", () => {
    for (const name of ["pwa-drawer-swipe", "opentrack-us-redaction", "nextjs-ram-autopsy", "bun-test-layout", "csv-export"]) {
      expect(skillNameProblem(name)).toBeUndefined();
      expect(isValidSkillName(name)).toBe(true);
    }
  });

  test("skillNameFrom normalises but never invents: unnameable text yields null, not a fallback", () => {
    expect(skillNameFrom("PWA drawer swipe")).toBe("pwa-drawer-swipe");
    expect(skillNameFrom("Clôturer le RAF openhermesbot-web migration 0021 appliquée")).toBeNull();
    expect(skillNameFrom("fix the thing")).toBeNull();
    expect(skillNameFrom("")).toBeNull();
  });

  test("description is required and capped at 60 on creation", () => {
    expect(skillDescriptionProblem("")).toBeDefined();
    expect(skillDescriptionProblem("Swipe-to-open drawer rules for the PWA shell.")).toBeUndefined();
    expect(skillDescriptionProblem("x".repeat(61))).toContain("60");
  });
});

describe("draft / approve / update / upsert", () => {
  test("draft then approve then update writes shipped SKILL.md; approve does not link by default", async () => {
    const home = await makeWorkspace("skill-fac-");
    const drafted = await draftSkill({
      name: "csv-export",
      description: "Export a list as CSV with a UTF-8 BOM.",
      goal: "Export CSV on the leads list",
      steps: ["write_file -> src/export.ts", "run_command"],
      artifacts: ["src/export.ts"],
      home,
    });
    expect(drafted.path).toContain("pending/skills/csv-export/SKILL.md");
    const pending = await readFile(drafted.path, "utf8");
    expect(pending).toContain("name: csv-export");
    expect(pending).toContain("description: Export a list as CSV with a UTF-8 BOM.");

    const approved = await approveSkill("csv-export", { home });
    expect("path" in approved).toBe(true);
    if ("path" in approved) expect(existsSync(approved.path)).toBe(true);

    const updated = await updateSkill("csv-export", { goal: "Export CSV + BOM", steps: ["write header", "stream rows"] }, { home });
    expect("path" in updated).toBe(true);
    if ("path" in updated) {
      const body = await readFile(updated.path, "utf8");
      expect(body).toContain("stream rows");
      expect(body).toContain("description: Export a list as CSV with a UTF-8 BOM.");
    }
  });

  test("upsert rejects a session-title name and an over-long description; update is exempt", async () => {
    const home = await makeWorkspace("skill-upsert-");
    await expect(
      upsertSkill({ name: "fix-csv-export", description: "x", steps: [], home }),
    ).rejects.toThrow(/session_prefix/);
    await expect(
      upsertSkill({ name: "csv-export", description: "y".repeat(61), steps: [], home }),
    ).rejects.toThrow(/60/);
    const first = await upsertSkill({ name: "csv-export", description: "Export as CSV.", steps: ["a"], home });
    expect(first.action).toBe("created");
    const second = await upsertSkill({ name: "csv-export", description: "z".repeat(80), steps: ["b"], home });
    expect(second.action).toBe("updated");
  });
});

describe("undoing the pollution", () => {
  async function fakeHarness(): Promise<string> {
    const h = await makeWorkspace("harness-home-");
    for (const d of [".claude/skills", ".grok/skills", ".codex/skills"]) await mkdir(join(h, d), { recursive: true });
    return h;
  }

  test("unlink removes only symlinks that point into the agentik store, keeps pinned and foreign entries", async () => {
    const home = await makeWorkspace("unlink-home-");
    const harnessHome = await fakeHarness();
    const a = await upsertSkill({ name: "csv-export", description: "Export as CSV.", steps: [], home });
    const b = await upsertSkill({ name: "pwa-drawer-swipe", description: "Drawer swipe rules.", steps: [], home });
    await linkHarnessSkill("csv-export", join(a.path, ".."), { harnessHome });
    await linkHarnessSkill("pwa-drawer-swipe", join(b.path, ".."), { harnessHome });
    // A skill that belongs to someone else: a real directory and a symlink elsewhere.
    await mkdir(join(harnessHome, ".claude/skills/ghostchrome"), { recursive: true });
    await writeFile(join(harnessHome, ".claude/skills/ghostchrome/SKILL.md"), "theirs", "utf8");
    const elsewhere = await makeWorkspace("elsewhere-");
    await symlink(elsewhere, join(harnessHome, ".claude/skills/other-tool"));
    await pinSkill("pwa-drawer-swipe", { home });

    const { removed, kept } = await unlinkHarnessSkills({ home, harnessHome });
    expect(removed).toHaveLength(3);
    expect(kept).toHaveLength(3);
    expect(existsSync(join(harnessHome, ".claude/skills/csv-export"))).toBe(false);
    expect((await lstat(join(harnessHome, ".claude/skills/pwa-drawer-swipe"))).isSymbolicLink()).toBe(true);
    expect(existsSync(join(harnessHome, ".claude/skills/ghostchrome/SKILL.md"))).toBe(true);
    expect((await lstat(join(harnessHome, ".claude/skills/other-tool"))).isSymbolicLink()).toBe(true);
    // Idempotent.
    expect((await unlinkHarnessSkills({ home, harnessHome })).removed).toHaveLength(0);
  });

  test("archive moves auto-generated skills, keeps hand-written and pinned ones, deletes nothing", async () => {
    const home = await makeWorkspace("archive-home-");
    const skills = join(home, "skills");
    const auto = async (name: string) => {
      await mkdir(join(skills, name), { recursive: true });
      await writeFile(join(skills, name, "SKILL.md"), `---\nname: ${name}\ndescription: >\n  ${AUTO_GENERATED_MARKER} for: x.\n---\n`, "utf8");
    };
    await auto("cre-e-moi-l-us-comple-te");
    await auto("learned-workflow");
    await auto("pinned-but-auto");
    await upsertSkill({ name: "nextjs-ram-autopsy", description: "Explain Next.js RAM usage.", steps: [], home });
    await pinSkill("pinned-but-auto", { home });

    const { archived, kept } = await archiveAutoGeneratedSkills({ home });
    expect(archived.sort()).toEqual(["cre-e-moi-l-us-comple-te", "learned-workflow"]);
    expect(kept.sort()).toEqual(["nextjs-ram-autopsy", "pinned-but-auto"]);
    expect(existsSync(join(skills, ".archive/learned-workflow/SKILL.md"))).toBe(true);
    expect(existsSync(join(skills, "learned-workflow"))).toBe(false);
    expect(existsSync(join(skills, "nextjs-ram-autopsy/SKILL.md"))).toBe(true);
  });
});
