#!/usr/bin/env bun
import { matchCommandRules } from "./command-policy.ts";
import { ConfigError, formatConfigError, readConfig } from "./config.ts";
import { currentDepth, depthProblem, nestedSymptom } from "./depth.ts";
import { mkdir } from "node:fs/promises";
import { resolve } from "node:path";
import {
  foreignWorkerArgs,
  harnessForName,
  resolveBackends,
  spawnCapture,
  spawnLines,
} from "./backends.ts";
import {
  describeStatus,
  HARNESSES,
  loadAvailability,
  type HarnessName, helpSupportsDenyRules } from "./availability.ts";
import {
  describeUntouched,
  snapshotArtifacts,
  untouchedArtifacts,
  type ArtifactSnapshot,
} from "./artifacts.ts";
import {
  consumeVerdictLine,
  newVerdict,
  summarizeVerdict,
  verdictArgs,
  verdictProblem, floorViolations } from "./verdict.ts";
import { formatReport, runLoop } from "./loop.ts";
import { defaultFetchImpl } from "./tools.ts";
import { retainNote, readHot } from "./memory.ts";
import { memoryFileLabel, memoryFilePath, memoryRemoveEntry, type MemoryTarget } from "./memory-store.ts";
import { formatSessionHit, searchSessions } from "./sessions.ts";
import { buildContext } from "./context.ts";
import { renderEnvelope, wrapUntrusted } from "./trust.ts";
import {
  classifyIncident,
  formatIncidentLine,
  getIncident,
  listIncidents,
  recordIncident,
  resolveIncident,
  type IncidentRecord,
} from "./incidents.ts";
import { formatIncidentForReview, formatReviewOutcome, runReview, type ReviewOutcome } from "./reviewer.ts";
import { getSession, latestSession } from "./sessions.ts";
import { readFile } from "node:fs/promises";
import { recallBeforeRun, reviewAfterRun, type SessionStatus } from "./review.ts";
import {
  approveSkill,
  archiveAutoGeneratedSkills,
  draftSkill,
  linkHarnessSkill,
  listSkills,
  pinSkill,
  skillNameProblem,
  unlinkHarnessSkills,
  updateSkill,
} from "./skill-factory.ts";
import { memoryPaths, agentikHome } from "./home.ts";
import { join } from "node:path";
import { approveMemory, approveSkillOps, formatPendingMemory, formatPendingSkills, rejectPending, type ApprovalOutcome } from "./approval.ts";
import { curateSkills, formatCurateResult, rollbackSkills } from "./curator.ts";
import { isPendingId, listPending, pendingCounts, readPending, type PendingMemoryOp, type PendingSkillOp } from "./pending.ts";
import { skillFile, skillTextProblem, viewSkill } from "./skill-ops.ts";
import { describeUsage, readSkillUsage, recordSkillUsage } from "./skill-usage.ts";
import {
  clampSubagentCount,
  isWorkerRole,
  MAX_SUBAGENTS,
  type OrchestratorDecision,
  type RunReport,
  type RunStatus,
} from "./types.ts";

function usage(): string {
  return `agentik — 3-role agentic development system
You are the supreme orchestrator. Two AI workers take bounded tasks.

Launch like your other CLIs:
  agentik "Create src/greet.txt containing AGENTIK_OK"
  agentik --yolo "fix the failing test"          # same posture as grok --yolo / cla / cc

Auto-run: each worker is re-invoked on tool results until it returns no
toolCalls or --max-steps. Low/medium tools execute immediately. High-blast
waits unless you passed --yolo (your session approval).
  agentik --backend cla "…"                      # workers = claude -p (cla flags)
  agentik --backend grok "…"                     # workers = grok --yolo --single --no-plan
  agentik --worker-a grok --worker-b cc "…"      # mix grok + codex --yolo

Commands:
  agentik [run] <goal> [options]
  agentik spawn --harness grok|codex|claude [--workspace DIR] [--role Korben] <task>
                               One non-interactive CLI process per foreign-harness slot.
                               Each harness runs its OWN full agent loop to natural
                               completion (multiple tool calls/turns) before exiting;
                               agentik does not drive the loop for you here:
                                 grok   -> grok --yolo --single … --no-subagents --no-plan
                                 codex  -> codex exec --yolo --skip-git-repo-check --ephemeral
                                 claude -> claude -p --dangerously-skip-permissions --effort high
                               The worker gets the same block "agentik context" prints (USER,
                               MEMORY, PROJECT MEMORY of that workspace, skills index, related
                               sessions, KNOWN FAILURES) as DATA in front of the task, capped
                               at 6000 chars; --no-context leaves it out.
                               Output streams live and agentik reads the harness's own event
                               stream, so it reports what the worker actually did (turns, tool
                               calls, stop reason) instead of trusting the exit code. The
                               harness is probed first: a CLI that is not authenticated exits 2
                               instead of being launched.
                               Exit codes: 0 done · 1 the CLI failed · 2 unusable harness
                               · 124 killed by --timeout, the task did NOT finish
                               · 125 the harness ended without doing the work.
  agentik context [--workspace DIR] [--profile P] ["<goal>"]
  agentik review ["<goal>"] [--transcript FILE | --session ID | --incident ID] [--backend sonnet|codex|claude]
                               Background review: a model reads what happened and decides what
                               to remember (MEMORY.md / USER.md) or which skill to patch/create.
                               Bounded: 16 iterations, 1 skill create, cap forces consolidation.
                               run does this automatically on live runs (--no-review to skip);
                               harvest --transcript FILE chains into it.
                               --incident ID is the postmortem: one question — why, and what
                               prevents it — answered with incident classify|resolve|merge,
                               a memory fact, or a skill Pitfalls patch (seen ≥2).
                               The block /ak reads before work: USER profile, MEMORY (GLOBAL
                               durable facts), PROJECT MEMORY (this workspace's own file,
                               only when --workspace is given and it is non-empty), the skills
                               index (name: description) and the top-6 sessions related to
                               the goal, filtered on the workspace.
  agentik memory search "<q>" [--workspace DIR] [--all] [--limit N]
                               Search sessions.sqlite (FTS5, diacritics-insensitive + trigram):
                               "cloturer" finds « clôturer », "drawr" finds "drawer".
                               "memory recall" is an alias.
  agentik memory hot | retain <fact> | remove "<exact entry or unique prefix>"
                          [--target memory|user|project] [--workspace DIR]
                               One memory file: --target memory = the GLOBAL MEMORY.md
                               (default, cap 2200), user = USER.md (1375), project = this
                               workspace's memory/projects/<slug>/MEMORY.md (2200; --workspace
                               DIR, default cwd). "hot" prints it; "retain" adds a fact (over
                               the cap the note is refused, consolidate first); "remove" drops
                               one entry by exact text or unique prefix — the human's pen: no
                               approval queue, a MEMORY.md.bak.<ts> copy is taken first; no
                               match or several matches exit 1 and list the candidates.
  agentik memory pending | approve <id|all> | reject <id|all>
                               With memory.writeApproval on in <home>/config.json, every memory
                               write (reviewer tool, retain) is staged under pending/memory/;
                               approve replays it (the cap applies then), reject drops it.
  agentik skills list | view <name> | draft|approve|update ... | pin|unpin|link|unlink|archive
                               "skills view <name>" prints a skill body and counts one view —
                               this is how /ak loads a skill from the index.
  agentik skills curate [--dry-run] [--stale-days 30] [--archive-days 90] [--rollback SNAPSHOT]
                               Curator: a skill not loaded for 30 days is marked stale, for 90
                               days it is moved to skills/.archive (pinned or human-made skills
                               are never archived). Never deletes. Snapshots skills/ to
                               skills/.snapshots/<iso>.tar.gz before changing anything and
                               logs every action in skills/.curator-ledger.json;
                               --rollback restores a snapshot (after taking one more).
  agentik skills pending | approve <id|all> | reject <id|all>
                               Same queue for skill_manage patch/create (skills.writeApproval).
  agentik harvest "<goal>" [--workspace DIR] [--artifact PATH] [--step TEXT]
                          [--status completed|failed|partial --cause TEXT] [--transcript FILE]
                               Records the session. --status failed|partial needs --cause: the
                               cause becomes an incident (see postmortem). Every non-zero
                               spawn, stalled task and backend switch is an incident too.
  agentik postmortem [--workspace DIR] [--since 7d|30d|ISO] [--all] [--json]
                               The incident log, grouped by cause (uncategorised last): every
                               non-zero spawn, stalled task, backend switch and declared
                               harvest failure, deduplicated by symptom (seen N×). Unresolved
                               incidents seen ≥2 show up in "agentik context" as KNOWN
                               FAILURES; seen once stays here. --all includes resolved ones.
  agentik postmortem classify <id> "<cause>" | resolve <id> "<fix>" | review <id>
                               review <id> = agentik review --incident <id>.
  agentik probe [--json] [--refresh-backends]

Options:
  --workspace DIR              Workspace root (default: cwd); stored on the session
  --profile NAME               Memory profile: default = ~/.agentik, any other name =
                               ~/.agentik/profiles/NAME (env AGENTIK_PROFILE)
  --agentik-home DIR           Explicit home, wins over --profile and AGENTIK_HOME
  --backend mock|auto|cla|claude|grok|codex|cc
                               Worker pair (default: mock; --yolo implies auto)
  --workers N                  Subagent count 1–${MAX_SUBAGENTS} (default 2, hard cap ${MAX_SUBAGENTS})
  --worker-a mock|cla|sonnet|opus|grok|codex|cc
  --worker-b mock|cla|sonnet|opus|grok|codex|cc
  --worker-c / --worker-d / --worker-e
                               Backends for extra subagents
  --yolo                       Session approval (you launched yolo) + live CLIs
  --max-steps N                Auto-run cap per worker task (default: 8)
  --timeout SECONDS            Wall clock for agentik spawn (default 1800, 0 = unbounded)
  --step-timeout SECONDS       Wall clock for one worker-CLI invocation (default 600)
  --refresh-backends           Re-probe the harnesses instead of reading the 15min cache
  --strict-backend             Fail instead of rerouting when a named harness is unusable
  --no-review                  run / harvest: skip the background review
  --allow-high-blast           spawn: run WITHOUT the high-blast floor (rm -rf, git push --force,
                               sudo, … are denied at the harness by default; codex gets a trusted
                               prompt line and after-the-fact detection). Says "floor DISABLED".
  --require-tools              spawn: a run that calls no tool is a failure (exit 125).
                               Pass it for implement/fix tasks, omit it for diagnostics.
  --expect-artifact PATH       spawn: this workspace path must be created, modified or
                               removed by the run, else exit 125. Repeatable.
  --raw                        spawn: the harness's own output, no verdict
  --no-context                 spawn: do not prepend the agentik context block (DATA) to the task
  --approve-high-blast         Explicit high-blast approval without --yolo
  --reject-high-blast          Reject pending high-blast tools
  --override stop|redirect     Stop or redirect the run
  --redirect-goal TEXT         New goal when --override redirect
  --json                       Print the full run report as JSON

Worker CLIs keep their native file/shell tools disabled; tool calls still go through
the gate. --backend auto only routes to a harness whose authenticated probe passes,
and a backend that dies mid-run is handed off to a live one (see "backend switches" in
the report). Exit 5 means a task stalled: it never produced a usable answer.
Test hook: AGENTIK_MOCK_STALL=worker_a…worker_e makes that mock worker stall (exit 5, incident).
`;
}

export async function main(argv = process.argv.slice(2)): Promise<number> {
  if (argv.length === 0 || argv[0] === "-h" || argv[0] === "--help") {
    console.log(usage());
    return 0;
  }
  const cmd = argv[0];
  // Fail closed on a broken config.json before any command that could write memory, skills,
  // sessions or spawn a worker. probe / context / postmortem never write and stay available.
  if (!CONFIG_EXEMPT.has(cmd)) {
    const problem = await preflightConfig(argv);
    if (problem !== undefined) return problem;
  }
  if (cmd === "probe") return probe(argv.slice(1));
  // A worker never spawns workers. Checked before any probe or backend resolution.
  {
    const nesting = cmd === "spawn" ? "spawn" : cmd === "run" || !KNOWN_COMMANDS.has(cmd) ? "run" : undefined;
    if (nesting && depthProblem(nesting)) return refuseNested(nesting, cmd === "spawn" || cmd === "run" ? argv.slice(1) : argv);
  }
  if (cmd === "spawn") return spawnForeign(argv.slice(1));
  if (cmd === "memory") return memoryCmd(argv.slice(1));
  if (cmd === "skill" || cmd === "skills") return skillCmd(argv.slice(1));
  if (cmd === "harvest") return harvestCmd(argv.slice(1));
  if (cmd === "context") return contextCmd(argv.slice(1));
  if (cmd === "review") return reviewCmd(argv.slice(1));
  if (cmd === "postmortem") return postmortemCmd(argv.slice(1));

  const runArgv = cmd === "run" ? argv.slice(1) : argv;
  const { goal, flags } = parseRun(runArgv);
  if (!goal) {
    console.error("missing goal");
    console.error(usage());
    return 2;
  }

  const workspace = resolve(flags.workspace ?? process.cwd());
  await mkdir(workspace, { recursive: true });
  const home = homeFor(flags);
  const backendSpec = flags.backend ?? (flags.yolo ? "auto" : "mock");
  const workerCount = clampSubagentCount(flags.workers ?? 2);
  const names = [flags.workerA, flags.workerB, flags.workerC, flags.workerD, flags.workerE];
  // Only probe when a real CLI could be routed to. A mock run must stay offline.
  const wantsLiveCli =
    harnessForName(backendSpec) !== null ||
    backendSpec === "auto" ||
    backendSpec === "yolo" ||
    names.some((n) => n && harnessForName(n) !== null);
  const availability = wantsLiveCli
    ? await loadAvailability({ home, refresh: flags.refreshBackends })
    : undefined;
  const routingNotes: string[] = [];
  // Test hook, read only here: the mock worker for that role stalls (empty act replies).
  const mockStall = process.env.AGENTIK_MOCK_STALL;
  if (mockStall !== undefined && !isWorkerRole(mockStall)) {
    console.error(`agentik: AGENTIK_MOCK_STALL="${mockStall}" is not a worker role (worker_a…worker_e)`);
    return 2;
  }
  let workerA;
  let workerB;
  let workers;
  try {
    ({ workerA, workerB, workers } = resolveBackends(backendSpec, flags.workerA, flags.workerB, {
      count: workerCount,
      names,
      availability: flags.strictBackend ? undefined : availability,
      notes: routingNotes,
      timeoutMs: flags.stepTimeout === undefined ? undefined : flags.stepTimeout * 1000,
      home,
      mockStall,
    }));
  } catch (err) {
    console.error(`agentik: ${err instanceof Error ? err.message : String(err)}`);
    return 2;
  }
  if (flags.strictBackend && availability) {
    const dead = [backendSpec, ...names]
      .filter((n): n is string => Boolean(n))
      .map((n) => harnessForName(n))
      .filter((h): h is HarnessName => h !== null)
      .filter((h) => !availability[h].loggedIn);
    if (dead.length) {
      console.error(
        `agentik: --strict-backend and ${[...new Set(dead)].join(", ")} not authenticated — run \`agentik probe\``,
      );
      return 2;
    }
  }
  for (const note of routingNotes) console.error(`agentik: ${note}`);
  const decisions: OrchestratorDecision[] = [];
  if (flags.approveHighBlast && !flags.yolo) decisions.push({ type: "approve" });
  if (flags.rejectHighBlast) decisions.push({ type: "reject" });
  if (flags.override) {
    decisions.push({
      type: "override",
      overrideAction: flags.override,
      redirectGoal: flags.redirectGoal,
    });
  }

  const live = backendSpec !== "mock" || Boolean(flags.workerA && flags.workerA !== "mock");
  if (!flags.json) {
    const hits = await recallBeforeRun({ goal, home, workspace });
    if (hits.length) {
      console.log(`memory recall:\n${hits.map((h) => `- ${h}`).join("\n")}`);
    }
  }
  const report = await runLoop({
    goal,
    workspace,
    workerA,
    workerB,
    workers,
    workerCount,
    decisions,
    fetchImpl: live ? defaultFetchImpl() : undefined,
    autoApproveHighBlast: Boolean(flags.yolo || flags.approveHighBlast),
    maxSteps: flags.maxSteps,
  });

  if (flags.json) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    console.log(formatReport(report));
  }

  const harvested = await reviewAfterRun({
    goal,
    report,
    home,
    workspace,
    profile: flags.profile,
    verdict: {
      tools: report.executedTools.length,
      blocked: report.blockedTools.length,
      stalled: report.stalledTasks.length,
      backendSwitches: report.backendSwitches.length,
    },
  });
  if (!flags.json) console.log(`memory: ${harvested.memoryLayer} #${harvested.sessionId}`);
  await recordRunIncidents({ goal, report, home, workspace, profile: flags.profile, quiet: flags.json });

  // Background review: a model decides what this run taught us. Live runs only — a mock run
  // has nothing to learn from — and skippable with --no-review.
  if (live && !flags.noReview) {
    const outcome = await runReview({
      goal,
      transcript: `${formatReport(report)}\n\nsynthesis:\n${report.synthesis}`,
      workspace,
      home,
      backend: workers.find((w) => !w.id.startsWith("mock")) ?? workerA,
      maxIterations: flags.maxIterations,
    });
    if (!flags.json) {
      console.log(formatReviewOutcome(outcome));
      await printPendingHint(home);
    }
  }

  return exitCodeFor(report);
}

/**
 * `agentik review "<goal>" [--transcript FILE | --session ID] [--backend …]`
 * Runs the background review on its own — the `/ak` conductor calls this after work, with a
 * transcript file of what happened, in place of the old code-side skill harvest.
 */
async function reviewCmd(args: string[]): Promise<number> {
  const { goal, flags } = parseRun(args);
  const home = homeFor(flags);
  let workspace = resolve(flags.workspace ?? process.cwd());
  let transcript = "";
  let reviewGoal = goal;
  let incident: IncidentRecord | undefined;
  if (flags.incident) {
    if (flags.transcript || flags.session) {
      console.error("agentik review: --incident cannot be combined with --transcript or --session");
      return 2;
    }
    const id = Number(flags.incident);
    incident = (Number.isInteger(id) && (await getIncident(id, { home }))) || undefined;
    if (!incident) {
      console.error(`agentik review: no incident #${flags.incident} (agentik postmortem lists them)`);
      return 2;
    }
    reviewGoal = reviewGoal || incident.goal;
    if (!flags.workspace && incident.workspace) workspace = incident.workspace;
    transcript = formatIncidentForReview(incident);
  }
  if (flags.transcript) {
    try {
      transcript = await readFile(flags.transcript, "utf8");
    } catch (err) {
      console.error(`agentik review: cannot read --transcript ${flags.transcript}: ${err instanceof Error ? err.message : String(err)}`);
      return 2;
    }
  }
  if (!transcript && !incident) {
    const session = flags.session
      ? await getSession(Number(flags.session), { home })
      : await latestSession({ home, workspace });
    if (!session) {
      console.error("agentik review: nothing to review — pass --transcript FILE, --session ID, or run something first");
      return 2;
    }
    reviewGoal = reviewGoal || session.goal;
    transcript = [
      `session #${session.id} [${session.createdAt}]`,
      `goal: ${session.goal}`,
      `workspace: ${session.workspace || "(unknown)"}`,
      `status: ${session.status}`,
      `summary: ${session.summary}`,
      `artifacts: ${session.artifacts.join(", ") || "none"}`,
      session.verdict ? `verdict: ${JSON.stringify(session.verdict)}` : "",
    ].filter(Boolean).join("\n");
  }
  if (!reviewGoal) {
    console.error("agentik review: a goal is required");
    return 2;
  }
  let backend;
  try {
    backend = await pickReviewBackend(flags.backend, home, flags.stepTimeout);
  } catch (err) {
    console.error(`agentik review: ${err instanceof Error ? err.message : String(err)}`);
    return 2;
  }
  const outcome: ReviewOutcome = await runReview({
    goal: reviewGoal,
    transcript,
    workspace,
    home,
    backend,
    maxIterations: flags.maxIterations,
    incident,
  });
  if (flags.json) console.log(JSON.stringify(outcome, null, 2));
  else {
    console.log(formatReviewOutcome(outcome));
    await printPendingHint(home);
  }
  // A backend that dies after the writes landed ended the review early, it did not undo it.
  const landed = outcome.memoryOps + outcome.projectOps + outcome.userOps + outcome.skillOps + outcome.incidentOps > 0;
  return outcome.stoppedBecause === "backend_error" && !landed ? 1 : 0;
}

const POSTMORTEM_USAGE =
  "usage: agentik postmortem [--workspace DIR] [--since 7d|30d|ISO] [--all] [--json]\n" +
  '       agentik postmortem classify <id> "<cause>" | resolve <id> "<fix>" | review <id> [review options]';

/** `7d`, `36h`, `30m` or an ISO timestamp -> ISO lower bound; undefined when it cannot be read. */
export function parseSince(text: string, now = Date.now()): string | undefined {
  const rel = /^(\d+)([dhm])$/.exec(text.trim());
  if (rel) {
    const n = Number(rel[1]);
    const ms = rel[2] === "d" ? 86_400_000 : rel[2] === "h" ? 3_600_000 : 60_000;
    return new Date(now - n * ms).toISOString();
  }
  const at = Date.parse(text);
  return Number.isFinite(at) ? new Date(at).toISOString() : undefined;
}

/**
 * `agentik postmortem`: the incident log for the human. List grouped by cause, or classify /
 * resolve by hand (the human is supreme; no cause length limit here), or hand one incident to
 * the reviewer (`review <id>` = `agentik review --incident <id>`).
 */
async function postmortemCmd(args: string[]): Promise<number> {
  const sub = args[0];
  if (sub === "classify" || sub === "resolve") {
    const id = Number(args[1]);
    const { goal: text, flags } = parseRun(args.slice(2));
    if (!Number.isInteger(id) || id <= 0 || !text) {
      console.error(POSTMORTEM_USAGE);
      return 2;
    }
    const home = homeFor(flags);
    const rec = sub === "classify" ? await classifyIncident(id, text, { home }) : await resolveIncident(id, text, { home });
    if (!rec) {
      console.error(`agentik postmortem: no incident #${id}`);
      return 1;
    }
    console.log(`${sub === "classify" ? "classified" : "resolved"} ${formatIncidentLine(rec)}${sub === "classify" ? ` · cause: ${rec.cause}` : ""}`);
    return 0;
  }
  if (sub === "review") {
    if (!args[1] || args[1].startsWith("--")) {
      console.error(POSTMORTEM_USAGE);
      return 2;
    }
    return reviewCmd(["--incident", args[1], ...args.slice(2)]);
  }
  if (sub && !sub.startsWith("--") && sub !== "list") {
    console.error(POSTMORTEM_USAGE);
    return 2;
  }
  const { flags } = parseRun(sub === "list" ? args.slice(1) : args);
  const home = homeFor(flags);
  let since: string | undefined;
  if (flags.since) {
    since = parseSince(flags.since);
    if (!since) {
      console.error(`agentik postmortem: cannot read --since ${flags.since} (7d, 36h, or an ISO timestamp)`);
      return 2;
    }
  }
  const incidents = await listIncidents({ home, workspace: flags.workspace, since, includeResolved: flags.all });
  if (flags.json) {
    console.log(JSON.stringify(incidents, null, 2));
    return 0;
  }
  if (!incidents.length) {
    console.log("(no incidents)");
    return 0;
  }
  const groups = new Map<string, IncidentRecord[]>();
  for (const inc of incidents) {
    const key = inc.cause || "";
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(inc);
  }
  const causes = [...groups.keys()].filter(Boolean);
  for (const cause of causes) {
    console.log(`cause: ${cause}`);
    for (const inc of groups.get(cause)!) console.log(`  ${formatIncidentLine(inc)}`);
  }
  if (groups.has("")) {
    console.log("uncategorised");
    for (const inc of groups.get("")!) console.log(`  ${formatIncidentLine(inc)}`);
  }
  return 0;
}

/** With write approval on, a "successful" review may have written nothing yet: say so. */
async function printPendingHint(home: string): Promise<void> {
  const counts = await pendingCounts({ home });
  if (counts.memory) console.log(`pending: ${counts.memory} memory op(s) await \`agentik memory approve <id|all>\` (agentik memory pending)`);
  if (counts.skills) console.log(`pending: ${counts.skills} skill op(s) await \`agentik skills approve <id|all>\` (agentik skills pending)`);
}

function printOutcomes(prefix: string, outcomes: ApprovalOutcome[]): number {
  if (!outcomes.length) {
    console.log(`${prefix}: nothing pending`);
    return 0;
  }
  let failed = 0;
  for (const o of outcomes) {
    console.log(`${o.ok ? "ok" : "refused"} #${o.id}: ${o.message}`);
    if (!o.ok) failed += 1;
  }
  return failed ? 1 : 0;
}

/** Cheapest authenticated harness first; `mock` is for tests and reviews nothing. */
async function pickReviewBackend(spec: string | undefined, home: string | undefined, stepTimeoutS?: number) {
  const timeoutMs = stepTimeoutS === undefined ? undefined : stepTimeoutS * 1000;
  if (spec) return resolveBackends(spec, undefined, undefined, { count: 1, timeoutMs, home }).workerA;
  const availability = await loadAvailability({ home });
  if (availability.claude.loggedIn) return resolveBackends("sonnet", undefined, undefined, { count: 1, timeoutMs, home }).workerA;
  if (availability.codex.loggedIn) return resolveBackends("codex", undefined, undefined, { count: 1, timeoutMs, home }).workerA;
  if (availability.grok.loggedIn) return resolveBackends("grok", undefined, undefined, { count: 1, timeoutMs, home }).workerA;
  throw new Error("no authenticated harness for the review — run `agentik probe`");
}

/**
 * Run statuses that are a failure of the run itself. `awaiting_approval` and `overridden` are
 * the human's own decisions, and `completed` with stalled tasks is covered per task below.
 */
const FAILED_RUN_STATUSES: ReadonlySet<RunStatus> = new Set<RunStatus>(["blocked", "rejected"]);

/**
 * One incident per stalled task, one per backend switch, one for a run that ended blocked or
 * rejected. The session already records the counts; the incident log records the *reason* so
 * the same failure surfaces in the next `agentik context`. Never fails the run.
 */
export async function recordRunIncidents(opts: {
  goal: string;
  report: Pick<RunReport, "status" | "stalledTasks" | "backendSwitches" | "blockedTools">;
  home?: string;
  workspace: string;
  profile?: string;
  quiet?: boolean;
}): Promise<number[]> {
  const { report } = opts;
  const profile = opts.profile ?? process.env.AGENTIK_PROFILE ?? "default";
  const base = { goal: opts.goal, workspace: opts.workspace, profile };
  const wanted: Array<{ harness?: string; backend?: string; symptom: string; errors?: string[] }> = [];
  for (const s of report.stalledTasks) {
    wanted.push({ harness: s.backend, backend: s.backend, symptom: `stalled ${s.assignee}@${s.backend}: ${s.reason}` });
  }
  for (const b of report.backendSwitches) {
    wanted.push({ harness: b.from, backend: b.to, symptom: `backend switch ${b.role} ${b.from}→${b.to}: ${b.reason}` });
  }
  if (FAILED_RUN_STATUSES.has(report.status)) {
    wanted.push({
      symptom: `run ${report.status}`,
      errors: report.blockedTools.slice(0, 20).map((t) => `${t.tool}: ${t.reason}`),
    });
  }
  const ids: number[] = [];
  for (const w of wanted) {
    try {
      const rec = await recordIncident({ ...base, ...w, errors: w.errors ?? [] }, { home: opts.home });
      ids.push(rec.id);
      if (!opts.quiet) console.log(`incident: #${rec.id} recorded (seen ${rec.seen}×) — ${w.symptom}`);
    } catch (err) {
      console.error(`agentik: could not record incident: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return ids;
}

/**
 * 0 ok · 1 unfinished · 3 rejected/blocked · 4 awaiting approval · 5 stalled.
 * A stalled task outranks the orchestrator's own `completed`: a worker that never produced a
 * readable answer did not do the work, and the caller must be able to see that in `$?`.
 */
export function exitCodeFor(report: RunReport): number {
  if (report.status === "rejected" || report.status === "blocked") return 3;
  if (report.status === "awaiting_approval") return 4;
  if (report.stalledTasks.length > 0) return 5;
  if (report.status === "overridden") return 0;
  if (report.status !== "completed") return 1;
  return 0;
}

/** The context block a spawned worker gets in front of its task; longer than this is cut. */
export const SPAWN_CONTEXT_CAP = 6000;
export const SPAWN_CONTEXT_ORIGIN = "agentik:context";

/**
 * `agentik context` for this goal and workspace, rendered as an UNTRUSTED envelope ("DATA ONLY",
 * same renderer as the reviewer's inputs), capped at SPAWN_CONTEXT_CAP chars. A context that
 * cannot be built is reported on stderr and left out: the task still runs.
 */
export async function spawnContextBlock(goal: string, workspace: string, home: string): Promise<string | undefined> {
  let block: string;
  try {
    block = await buildContext({ goal, workspace, home });
  } catch (err) {
    console.error(`agentik spawn: could not build context: ${err instanceof Error ? err.message : String(err)}`);
    return undefined;
  }
  const body = block.length > SPAWN_CONTEXT_CAP ? `${block.slice(0, SPAWN_CONTEXT_CAP)}…[truncated]` : block;
  return renderEnvelope(wrapUntrusted(body, SPAWN_CONTEXT_ORIGIN, "retrieved"));
}

/** stderr of a CLI whose argv parser refused the floor flags. */
const ARGV_REJECTED = /(unknown|invalid|unrecognized|unexpected|bad)[^\n]{0,80}(deny|disallowed|settings)|(deny|disallowed|settings)[^\n]{0,80}(unknown|invalid|unrecognized|unexpected|not (a )?valid)/i;

async function spawnForeign(args: string[]): Promise<number> {
  const { goal, flags } = parseRun(args);
  const harnessRaw = (flags.harness ?? flags.backend ?? "").toLowerCase();
  const harness =
    harnessRaw === "cc" || harnessRaw === "codex"
      ? "codex"
      : harnessRaw === "cla" || harnessRaw === "claude" || harnessRaw === "sonnet" || harnessRaw === "opus"
        ? "claude"
        : harnessRaw === "grok"
          ? "grok"
          : null;
  if (!harness || !goal) {
    console.error("usage: agentik spawn --harness grok|codex|claude [--workspace DIR] [--role NAME] <task>");
    return 2;
  }
  const availability = await loadAvailability({ home: homeFor(flags) });
  const status = availability[harness];
  if (!status.loggedIn) {
    console.error(
      `agentik spawn: ${harness} is ${describeStatus(status)} (${status.detail}) — not spawning a dead harness`,
    );
    const alive = HARNESSES.filter((h) => availability[h].loggedIn);
    console.error(
      alive.length
        ? `usable right now: ${alive.join(", ")}`
        : "no harness is authenticated — run `agentik probe`",
    );
    return 2;
  }

  // The high-blast floor: HIGH_BLAST_DENY_RULES handed to the harness as deny rules. A claude
  // or grok that does not advertise the flag would run with no floor at all — refuse instead.
  const floor = !flags.allowHighBlast;
  if (!floor) {
    console.error("agentik spawn: high-blast floor DISABLED (--allow-high-blast) — rm -rf, git push --force, sudo… are NOT denied for this worker");
  } else if (harness === "codex") {
    console.error("agentik spawn: codex has no deny flag — the floor is a trusted prompt line; violations are detected after the fact");
  } else {
    const supports = status.supportsDenyRules ?? (await helpSupportsDenyRules(harness));
    if (!supports) {
      console.error(
        `agentik spawn: ${harness} does not advertise deny rules in --help (${harness === "grok" ? "--deny" : "--disallowedTools / --settings"}) — refusing to spawn without the high-blast floor; pass --allow-high-blast to run without it`,
      );
      return 2;
    }
  }

  const workspace = resolve(flags.workspace ?? process.cwd());
  const role = flags.role ? `You are ${flags.role}. ` : "";
  const bounded = `${role}Bounded task (no nested subagents, stay in ${workspace}):\n${goal}`;
  // The worker sees what the conductor sees — memory, this workspace's project memory, skills,
  // related sessions, known failures — as DATA in front of the task, never as instructions.
  const context = flags.noContext ? undefined : await spawnContextBlock(goal, workspace, homeFor(flags));
  const prompt = context ? `${context}\n\n${bounded}` : bounded;
  const expected = flags.expectArtifacts ?? [];
  // Murphy: a failure that is not written down happens again. Every non-zero exit leaves an
  // incident (same symptom on the same harness and workspace -> seen+1). Recording never
  // changes the exit code: if the log itself fails, say so and return the same code.
  const noteIncident = async (code: number, symptom: string, extra?: { stopReason?: string; errors?: string[] }) => {
    try {
      const rec = await recordIncident(
        {
          goal,
          workspace,
          profile: flags.profile ?? process.env.AGENTIK_PROFILE ?? "default",
          harness,
          backend: harness,
          exitCode: code,
          stopReason: extra?.stopReason,
          errors: extra?.errors ?? [],
          symptom,
        },
        { home: homeFor(flags) },
      );
      console.error(`agentik spawn: incident #${rec.id} recorded (seen ${rec.seen}×)`);
    } catch (err) {
      console.error(`agentik spawn: could not record incident: ${err instanceof Error ? err.message : String(err)}`);
    }
  };
  const fail = async (code: number, symptom: string, extra?: { stopReason?: string; errors?: string[] }) => {
    await noteIncident(code, symptom, extra);
    return code;
  };
  let before: ArtifactSnapshot[] = [];
  try {
    before = await snapshotArtifacts(workspace, expected);
  } catch (err) {
    console.error(`agentik spawn: ${err instanceof Error ? err.message : String(err)}`);
    return 2;
  }
  const timeoutMs = (flags.timeout ?? DEFAULT_SPAWN_TIMEOUT_S) * 1000;
  const timedOutSymptom = () =>
    `${harness} killed after ${Math.round(timeoutMs / 1000)}s (timeout) — the task did NOT finish, partial work may be on disk`;
  const timedOutMsg = () => `agentik spawn: ${timedOutSymptom()}`;

  if (flags.raw) {
    // Opt-out: the harness's own rendering, no verdict.
    const { bin, args: rawArgs } = foreignWorkerArgs(harness, prompt, workspace, [], { allowHighBlast: !floor });
    if (floor) console.error("agentik spawn: --raw reads no stream — floor violations cannot be detected after the fact on this run");
    const res = await spawnCapture(bin, rawArgs, timeoutMs, workspace, { stream: true });
    if (res.timedOut) {
      console.error(timedOutMsg());
      return fail(124, timedOutSymptom());
    }
    if (res.exitCode !== 0) return fail(1, `${harness} exited ${res.exitCode}`);
    const untouchedRaw = await untouchedArtifacts(workspace, before);
    if (untouchedRaw.length > 0) {
      const symptom = describeUntouched(untouchedRaw);
      console.error(`agentik spawn: ${symptom}`);
      return fail(125, symptom);
    }
    return 0;
  }

  // Read the harness's own event stream. Exit code alone cannot tell a worker that did the
  // job from one that narrated an intention and stopped — both exit 0.
  const { bin, args: streamArgs } = foreignWorkerArgs(harness, prompt, workspace, verdictArgs(harness), { allowHighBlast: !floor });
  const verdict = newVerdict(harness);
  const startedAt = Date.now();
  const res = await spawnLines(bin, streamArgs, timeoutMs, workspace, (line) =>
    consumeVerdictLine(verdict, line, {
      onText: (chunk) => process.stdout.write(chunk),
      onTool: (name, detail) => process.stderr.write(`  ⟩ ${name}${detail ? ` ${detail}` : ""}\n`),
    }),
  );
  process.stdout.write("\n");
  console.error(`agentik spawn: ${summarizeVerdict(verdict)}`);
  // Only an incomplete turn makes these errors; on a completed turn they are harness notes
  // (codex, for one, emits a benign config warning on every successful run).
  const label = verdict.completed ? "note" : "harness error";
  for (const e of verdict.errors) console.error(`agentik spawn: ${label} — ${e}`);

  // The floor, after the fact: a high-blast command the harness reports having run (and did
  // not deny itself) is an incident whatever the exit code — the exit code is never changed.
  const violations = floorViolations(verdict);
  for (const cmd of verdict.denied) {
    if (matchCommandRules(cmd).level !== "medium") console.error(`agentik spawn: denied by the floor — ${cmd.slice(0, 120)}`);
  }
  if (violations.length > 0) {
    for (const vi of violations) {
      console.error(`agentik spawn: ${floor ? "FLOOR VIOLATION" : "high-blast command (floor disabled)"} — ${harness} ran "${vi.command.slice(0, 120)}" (${vi.rules.join(", ")})`);
    }
    if (floor) {
      await noteIncident(res.exitCode, `${harness} ran a high-blast command despite the floor: ${violations.map((vi) => vi.rules[0]).join(", ")}`, {
        stopReason: verdict.stopReason,
        errors: [...violations.map((vi) => `ran: ${vi.command.slice(0, 160)}`), ...verdict.errors],
      });
    }
  }

  const detail = { stopReason: verdict.stopReason, errors: verdict.errors };
  if (res.timedOut) {
    console.error(timedOutMsg());
    return fail(124, timedOutSymptom(), detail);
  }
  if (res.exitCode !== 0) {
    if (res.stderr.trim()) process.stderr.write(res.stderr);
    // A CLI that rejects the deny rules as argv dies at once, before any event.
    if (floor && verdict.events === 0 && Date.now() - startedAt < 5_000 && ARGV_REJECTED.test(res.stderr)) {
      const symptom = `${harness} rejected the deny rules (argv) — exit ${res.exitCode}; the floor could not be installed`;
      console.error(`agentik spawn: ${symptom}`);
      return fail(1, symptom, { ...detail, errors: [res.stderr.trim().split("\n")[0].slice(0, 200), ...verdict.errors] });
    }
    return fail(1, `${harness} exited ${res.exitCode}`, detail);
  }
  const problem = verdictProblem(verdict, { requireTools: flags.requireTools });
  if (problem) {
    console.error(`agentik spawn: ${problem} — treating this as unfinished, not as success`);
    return fail(125, problem, detail);
  }
  // The stream proves tools ran; only the filesystem proves the deliverable moved.
  const untouched = await untouchedArtifacts(workspace, before);
  if (untouched.length > 0) {
    const symptom = describeUntouched(untouched);
    console.error(`agentik spawn: ${symptom} — treating this as unfinished, not as success`);
    return fail(125, symptom, detail);
  }
  if (expected.length > 0) {
    console.error(`agentik spawn: ${expected.length} expected artifact(s) verified on disk`);
  }
  return 0;
}

/**
 * Reports what each harness can actually do right now. `--version` used to stand in for this
 * and reported an expired or logged-out CLI as "ok", which is how dead backends stayed in the
 * rotation. Now it is a real authenticated status call per harness (no model tokens spent).
 */
async function probe(args: string[] = []): Promise<number> {
  const { flags } = parseRun(args);
  const map = await loadAvailability({
    home: homeFor(flags),
    refresh: flags.refreshBackends ?? true,
  });
  if (flags.json) {
    console.log(JSON.stringify(map, null, 2));
  } else {
    for (const h of HARNESSES) {
      console.log(`${h}: ${describeStatus(map[h])} — ${map[h].detail}`);
    }
  }
  return HARNESSES.some((h) => map[h].loggedIn) ? 0 : 1;
}

export function parseRun(args: string[]): {
  goal: string;
  flags: {
    workspace?: string;
    backend?: string;
    workerA?: string;
    workerB?: string;
    workerC?: string;
    workerD?: string;
    workerE?: string;
    workers?: number;
    approveHighBlast?: boolean;
    rejectHighBlast?: boolean;
    yolo?: boolean;
    maxSteps?: number;
    override?: "stop" | "redirect";
    redirectGoal?: string;
    json?: boolean;
    harness?: string;
    role?: string;
    agentikHome?: string;
    goalFlag?: string;
    timeout?: number;
    stepTimeout?: number;
    refreshBackends?: boolean;
    strictBackend?: boolean;
    requireTools?: boolean;
    raw?: boolean;
    noContext?: boolean;
    expectArtifacts?: string[];
    linkHarness?: boolean;
    description?: string;
    profile?: string;
    transcript?: string;
    session?: string;
    noReview?: boolean;
    allowHighBlast?: boolean;
    maxIterations?: number;
    all?: boolean;
    limit?: number;
    dryRun?: boolean;
    staleDays?: number;
    archiveDays?: number;
    rollback?: string;
    status?: string;
    cause?: string;
    incident?: string;
    since?: string;
    target?: string;
  };
} {
  const flags: Record<string, string | boolean> = {};
  const positional: string[] = [];
  const expectArtifacts: string[] = [];
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === "--json") flags.json = true;
    else if (a === "--yolo") flags.yolo = true;
    else if (a === "--agentik-home") {
      flags["agentik-home"] = args[i + 1];
      i++;
    }
    else if (a === "--workers") {
      flags.workers = args[i + 1];
      i++;
    }
    else if (a === "--max-steps") {
      flags.maxSteps = args[i + 1];
      i++;
    }
    else if (a === "--approve-high-blast") flags.approveHighBlast = true;
    else if (a === "--reject-high-blast") flags.rejectHighBlast = true;
    else if (a === "--refresh-backends") flags.refreshBackends = true;
    else if (a === "--strict-backend") flags.strictBackend = true;
    else if (a === "--require-tools") flags.requireTools = true;
    else if (a === "--allow-high-blast") flags.allowHighBlast = true;
    else if (a === "--raw") flags.raw = true;
    else if (a === "--no-context") flags.noContext = true;
    else if (a === "--link-harness") flags.linkHarness = true;
    else if (a === "--no-review") flags.noReview = true;
    else if (a === "--max-iterations") {
      flags.maxIterations = args[i + 1];
      i++;
    }
    else if (a === "--all") flags.all = true;
    else if (a === "--dry-run") flags.dryRun = true;
    else if (a === "--expect-artifact" && args[i + 1]) {
      expectArtifacts.push(args[++i]);
    }
    else if (a.startsWith("--")) {
      const key = a.slice(2);
      const val = args[i + 1];
      if (!val || val.startsWith("--")) {
        flags[key] = true;
      } else {
        flags[key] = val;
        i++;
      }
    } else positional.push(a);
  }
  const goal = positional.join(" ").trim();
  const override = flags.override;
  return {
    goal,
    flags: {
      workspace: str(flags.workspace),
      backend: str(flags.backend),
      workerA: str(flags["worker-a"]),
      workerB: str(flags["worker-b"]),
      workerC: str(flags["worker-c"]),
      workerD: str(flags["worker-d"]),
      workerE: str(flags["worker-e"]),
      workers: Number.isFinite(Number(flags.workers)) ? Number(flags.workers) : undefined,
      approveHighBlast: Boolean(flags.approveHighBlast),
      rejectHighBlast: Boolean(flags.rejectHighBlast),
      yolo: Boolean(flags.yolo),
      maxSteps: Number.isFinite(Number(flags.maxSteps)) && Number(flags.maxSteps) > 0
        ? Number(flags.maxSteps)
        : undefined,
      override: override === "stop" || override === "redirect" ? override : undefined,
      redirectGoal: str(flags["redirect-goal"]),
      json: Boolean(flags.json),
      harness: str(flags.harness),
      role: str(flags.role),
      agentikHome: str(flags["agentik-home"]),
      goalFlag: str(flags.goal),
      timeout: nonNegative(flags.timeout),
      stepTimeout: nonNegative(flags["step-timeout"]),
      refreshBackends: Boolean(flags.refreshBackends),
      strictBackend: Boolean(flags.strictBackend),
      requireTools: Boolean(flags.requireTools),
      allowHighBlast: Boolean(flags.allowHighBlast),
      raw: Boolean(flags.raw),
      noContext: Boolean(flags.noContext),
      expectArtifacts,
      linkHarness: Boolean(flags.linkHarness),
      description: str(flags.description),
      profile: str(flags.profile),
      transcript: str(flags.transcript),
      session: str(flags.session),
      noReview: Boolean(flags.noReview),
      maxIterations:
        Number.isFinite(Number(flags.maxIterations)) && Number(flags.maxIterations) > 0
          ? Number(flags.maxIterations)
          : undefined,
      all: Boolean(flags.all),
      limit: positive(flags.limit),
      dryRun: Boolean(flags.dryRun),
      staleDays: nonNegative(flags["stale-days"]),
      archiveDays: nonNegative(flags["archive-days"]),
      rollback: str(flags.rollback),
      status: str(flags.status),
      cause: str(flags.cause),
      incident: str(flags.incident),
      since: str(flags.since),
      target: str(flags.target),
    },
  };
}

function positive(v: string | boolean | undefined): number | undefined {
  if (typeof v !== "string") return undefined;
  const n = Number(v);
  return Number.isInteger(n) && n > 0 ? n : undefined;
}

/** --agentik-home > AGENTIK_HOME > --profile / AGENTIK_PROFILE / default. */
function homeFor(flags: { agentikHome?: string; profile?: string }): string {
  return agentikHome(flags.agentikHome, flags.profile);
}

/** The scan a skill body gets on link, as a warning for `pin`. Undefined when clean or absent. */
async function skillBodyProblem(name: string, home: string): Promise<string | undefined> {
  try {
    return skillTextProblem(await readFile(skillFile(name, home), "utf8"));
  } catch {
    return undefined;
  }
}

const CONFIG_EXEMPT = new Set(["probe", "context", "postmortem"]);
const KNOWN_COMMANDS = new Set(["probe", "spawn", "memory", "skill", "skills", "harvest", "context", "review", "postmortem", "run"]);

/** Exit 2 with the depth message; the refusal is an incident so the conductor sees it next time. */
async function refuseNested(cmd: "spawn" | "run", argv: string[]): Promise<number> {
  const problem = depthProblem(cmd)!;
  console.error(`agentik: ${problem}`);
  const parsed = parseRun(argv);
  const workspace = resolve(parsed.flags.workspace ?? process.cwd());
  try {
    const rec = await recordIncident(
      {
        goal: parsed.goal || parsed.flags.goalFlag || `agentik ${cmd}`,
        workspace,
        profile: parsed.flags.profile ?? process.env.AGENTIK_PROFILE ?? "default",
        harness: "agentik",
        backend: parsed.flags.harness ?? parsed.flags.backend ?? "",
        exitCode: 2,
        stopReason: "nested",
        errors: [problem],
        symptom: nestedSymptom(cmd),
      },
      { home: homeFromArgv(argv) },
    );
    console.error(`agentik: incident #${rec.id} recorded (seen ${rec.seen}×, depth ${currentDepth()})`);
  } catch (err) {
    console.error(`agentik: could not record incident: ${err instanceof Error ? err.message : String(err)}`);
  }
  return 2;
}

/** The home the command will use, from the raw argv (before any subcommand parses its flags). */
function homeFromArgv(argv: string[]): string {
  let agentikHomeFlag: string | undefined;
  let profile: string | undefined;
  for (let i = 0; i < argv.length - 1; i++) {
    if (argv[i] === "--agentik-home") agentikHomeFlag = argv[i + 1];
    else if (argv[i] === "--profile") profile = argv[i + 1];
  }
  return homeFor({ agentikHome: agentikHomeFlag, profile });
}

/** Exit code when `<home>/config.json` is unusable, `undefined` when it is fine or absent. */
async function preflightConfig(argv: string[]): Promise<number | undefined> {
  try {
    await readConfig({ home: homeFromArgv(argv) });
    return undefined;
  } catch (err) {
    if (err instanceof ConfigError) {
      console.error(`agentik: ${formatConfigError(err)}`);
      return 2;
    }
    throw err;
  }
}

/** `--timeout 0` is meaningful (no bound), so 0 must survive the parse. */
function nonNegative(v: string | boolean | undefined): number | undefined {
  if (typeof v !== "string") return undefined;
  const n = Number(v);
  return Number.isFinite(n) && n >= 0 ? n : undefined;
}

const HARVEST_USAGE =
  'usage: agentik harvest "<goal>" [--workspace DIR] [--artifact PATH] [--step TEXT] [--transcript FILE]\n' +
  "       [--status completed|failed|partial] [--cause TEXT]   (failed|partial require --cause)";

const HARVEST_STATUSES = new Set<SessionStatus>(["completed", "failed", "partial"]);

async function harvestCmd(args: string[]): Promise<number> {
  const { goal, flags } = parseRun(args);
  const harvestGoal = goal || flags.goalFlag || "";
  if (!harvestGoal) {
    console.error(HARVEST_USAGE);
    return 2;
  }
  const status = (flags.status ?? "completed") as SessionStatus;
  if (!HARVEST_STATUSES.has(status)) {
    console.error(`agentik harvest: --status must be completed, failed or partial (got "${flags.status}")`);
    console.error(HARVEST_USAGE);
    return 2;
  }
  const cause = flags.cause?.trim() ?? "";
  if (status !== "completed" && !cause) {
    console.error(`agentik harvest: --status ${status} — a failure needs a cause (--cause TEXT)`);
    console.error(HARVEST_USAGE);
    return 2;
  }
  const artifacts: string[] = [];
  const steps: string[] = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--artifact" && args[i + 1]) artifacts.push(args[++i]);
    if (args[i] === "--step" && args[i + 1]) steps.push(args[++i]);
  }
  const executedTools = steps.map((s) => {
    const [tool, artifact] = s.split("->").map((x) => x.trim());
    return { tool: tool || "step", args: {}, output: s, artifact };
  });
  const workspace = resolve(flags.workspace ?? process.cwd());
  const harvested = await reviewAfterRun({
    goal: harvestGoal,
    report: {
      status,
      executedTools,
      artifacts,
    },
    home: homeFor(flags),
    // The help says "default: cwd"; a blank workspace would hide this session from every
    // workspace-filtered search.
    workspace,
    profile: flags.profile,
  });
  console.log(`memory: ${harvested.memoryLayer} #${harvested.sessionId}`);
  if (status !== "completed") {
    // The conductor named the cause; that is the symptom until a postmortem classifies it.
    // The session is already recorded; a failure to log the incident must not undo that.
    try {
      const rec = await recordIncident(
        {
          goal: harvestGoal,
          workspace,
          profile: flags.profile ?? process.env.AGENTIK_PROFILE ?? "default",
          harness: undefined,
          errors: [],
          symptom: cause,
        },
        { home: homeFor(flags) },
      );
      console.log(`incident: #${rec.id} recorded (seen ${rec.seen}×) — agentik postmortem review ${rec.id}`);
    } catch (err) {
      console.error(`agentik harvest: could not record incident: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  if (flags.transcript && !flags.noReview) {
    // The conductor wrote down what happened; hand it to the reviewer in the same call.
    return reviewCmd([
      harvestGoal,
      "--transcript",
      flags.transcript,
      "--workspace",
      flags.workspace ?? process.cwd(),
      ...(flags.agentikHome ? ["--agentik-home", flags.agentikHome] : []),
      ...(flags.profile ? ["--profile", flags.profile] : []),
      ...(flags.backend ? ["--backend", flags.backend] : []),
    ]);
  }
  console.log("skill: none here — the model-driven review decides (agentik review, or harvest --transcript FILE)");
  return 0;
}

const MEMORY_USAGE =
  'usage: agentik memory search "<query>" [--workspace DIR] [--all] [--limit N] | recall (alias)\n' +
  '       agentik memory hot | retain <fact> | remove "<exact entry or unique prefix>"  [--target memory|user|project] [--workspace DIR]\n' +
  "       agentik memory pending | approve <id|all> | reject <id|all>";

/** `--target` (default memory); `project` scopes to `--workspace` or the cwd. */
function memoryTargetFor(flags: { target?: string; workspace?: string }): { target: MemoryTarget; workspace?: string } | { error: string } {
  const raw = flags.target ?? "memory";
  if (raw !== "memory" && raw !== "user" && raw !== "project") {
    return { error: `unknown --target "${raw}" (memory | user | project)` };
  }
  return { target: raw, workspace: raw === "project" ? resolve(flags.workspace ?? process.cwd()) : undefined };
}

async function memoryCmd(args: string[]): Promise<number> {
  const sub = args[0];
  const { goal, flags } = parseRun(args.slice(1));
  const home = homeFor(flags);
  if (sub === "hot" || sub === "retain" || sub === "remove") {
    const scope = memoryTargetFor(flags);
    if ("error" in scope) {
      console.error(`agentik memory ${sub}: ${scope.error}`);
      return 2;
    }
    const { target, workspace } = scope;
    if (sub === "hot") {
      if (target === "memory") {
        process.stdout.write((await readHot({ home })) || "(empty HOT MEMORY.md)\n");
        return 0;
      }
      let body = "";
      try {
        body = await readFile(memoryFilePath(target, { home, workspace }), "utf8");
      } catch {
        body = "";
      }
      process.stdout.write(body || `(empty ${memoryFileLabel(target)}${workspace ? ` for ${workspace}` : ""})\n`);
      return 0;
    }
    if (!goal) {
      console.error(sub === "retain" ? "usage: agentik memory retain <note> [--target memory|user|project] [--workspace DIR]" : MEMORY_USAGE);
      return 2;
    }
    if (sub === "retain") {
      const r = await retainNote(goal, { home, target, workspace });
      console.log(r.layer === "rejected" ? `rejected: ${r.reason}` : `${r.layer} ${r.path}`);
      if (r.layer === "pending") console.log(`memory.writeApproval is on — ${r.reason}`);
      return r.layer === "rejected" ? 3 : 0;
    }
    // remove: the human's pen — no approval queue, a backup first, exact or unique-prefix match.
    const r = await memoryRemoveEntry(target, goal, { home, workspace });
    if (!r.ok) {
      console.error(`agentik memory remove: ${r.message}`);
      for (const c of r.candidates) console.error(`  § ${c}`);
      return 1;
    }
    console.log(`removed: ${r.removed}`);
    console.log(`backup: ${r.backup}`);
    console.log(`${memoryFileLabel(target)} ${r.usage.used}/${r.usage.cap} chars`);
    return 0;
  }
  if (sub === "pending") {
    console.log(formatPendingMemory(await listPending<PendingMemoryOp>("memory", { home })));
    return 0;
  }
  if (sub === "approve" || sub === "reject") {
    const id = args[1];
    if (!id) {
      console.error(MEMORY_USAGE);
      return 2;
    }
    const res = sub === "approve" ? await approveMemory(id, { home }) : await rejectPending("memory", id, { home });
    if ("error" in res) {
      console.error(`agentik memory ${sub}: ${res.error}`);
      return 1;
    }
    return printOutcomes(`memory ${sub}`, res);
  }
  if (sub === "search" || sub === "recall") {
    if (!goal) {
      console.error(MEMORY_USAGE);
      return 2;
    }
    const hits = await searchSessions(goal, {
      home,
      workspace: flags.workspace,
      all: flags.all,
      limit: flags.limit ?? 6,
    });
    console.log(hits.length ? hits.map((h) => `- ${formatSessionHit(h)}`).join("\n") : "(no hits)");
    return 0;
  }
  console.error(MEMORY_USAGE);
  return 2;
}

/** The block `/ak` reads at session open. `--workspace` scopes the related sessions. */
async function contextCmd(args: string[]): Promise<number> {
  const { goal, flags } = parseRun(args);
  const block = await buildContext({
    home: homeFor(flags),
    workspace: flags.workspace ? resolve(flags.workspace) : undefined,
    goal: goal || flags.goalFlag,
  });
  process.stdout.write(block);
  return 0;
}

const SKILL_USAGE =
  "usage: agentik skill list | view <name> | draft <name> --description \"…\" <goal> | approve <name> [--link-harness] | update <name> <goal>\n" +
  "       agentik skills unlink | archive | pin <name> | unpin <name> | link <name>\n" +
  "       agentik skills curate [--dry-run] [--stale-days N] [--archive-days N] [--rollback SNAPSHOT]\n" +
  "       agentik skills pending | approve <id|all> | reject <id|all>";

async function skillCmd(args: string[]): Promise<number> {
  const sub = args[0];
  const { goal, flags } = parseRun(args.slice(1));
  const home = homeFor(flags);
  if (sub === "list") {
    const [{ pending, approved, archived, pinned }, usage, counts] = await Promise.all([
      listSkills({ home }),
      readSkillUsage({ home }),
      pendingCounts({ home }),
    ]);
    console.log(`pending: ${pending.join(", ") || "(none)"}`);
    console.log(approved.length ? "approved:" : "approved: (none)");
    for (const name of approved) console.log(`  - ${name} [${describeUsage(usage[name])}]`);
    console.log(`pinned: ${pinned.join(", ") || "(none)"}`);
    console.log(`archived: ${archived.length}${archived.length ? ` (${archived.join(", ")})` : ""}`);
    if (counts.skills) console.log(`pending skill ops: ${counts.skills} (agentik skills pending)`);
    return 0;
  }
  if (sub === "view") {
    const name = args[1];
    if (!name) {
      console.error(SKILL_USAGE);
      return 2;
    }
    const body = await viewSkill(name, { home });
    if (body === undefined) {
      console.error(`agentik skills view: no skill named ${name}`);
      return 1;
    }
    process.stdout.write(body.endsWith("\n") ? body : `${body}\n`);
    return 0;
  }
  if (sub === "curate") {
    if (flags.rollback) {
      const r = await rollbackSkills(flags.rollback, { home });
      if ("error" in r) {
        console.error(`agentik skills curate --rollback: ${r.error}`);
        return 1;
      }
      console.log(`rollback: restored ${r.restored} — safety snapshot ${r.safetySnapshot}`);
      return 0;
    }
    const result = await curateSkills({ home, dryRun: flags.dryRun, staleDays: flags.staleDays, archiveDays: flags.archiveDays });
    console.log(formatCurateResult(result));
    return 0;
  }
  if (sub === "pending") {
    console.log(formatPendingSkills(await listPending<PendingSkillOp>("skills", { home })));
    return 0;
  }
  if (sub === "reject") {
    const id = args[1];
    if (!id) {
      console.error(SKILL_USAGE);
      return 2;
    }
    const res = await rejectPending("skills", id, { home });
    if ("error" in res) {
      console.error(`agentik skills reject: ${res.error}`);
      return 1;
    }
    return printOutcomes("skills reject", res);
  }
  if (sub === "draft") {
    const name = args[1];
    const rest = parseRun(args.slice(2));
    if (!name || !rest.goal || !rest.flags.description) {
      console.error(SKILL_USAGE);
      return 2;
    }
    const problem = skillNameProblem(name);
    if (problem) {
      console.error(`agentik: invalid skill name "${name}": ${problem} — names are class-level, not session titles`);
      return 2;
    }
    try {
      const drafted = await draftSkill({
        name,
        description: rest.flags.description,
        goal: rest.goal,
        steps: ["Captured from CLI draft."],
        home: rest.flags.agentikHome ? homeFor(rest.flags) : home,
      });
      console.log(drafted.path);
      return 0;
    } catch (err) {
      console.error(`agentik: ${err instanceof Error ? err.message : String(err)}`);
      return 2;
    }
  }
  if (sub === "approve") {
    const name = args[1];
    if (!name) {
      console.error(SKILL_USAGE);
      return 2;
    }
    // `approve all` / `approve <id>` is the staged-op queue; `approve <name>` a human draft.
    if (name === "all" || (isPendingId(name) && (await readPending("skills", name, { home })))) {
      const res = await approveSkillOps(name, { home });
      if ("error" in res) {
        console.error(`agentik skills approve: ${res.error}`);
        return 1;
      }
      return printOutcomes("skills approve", res);
    }
    // Linking is opt-in: a linked skill sits in every prompt of every harness, every turn.
    const ok = await approveSkill(name, { home, linkHarness: flags.linkHarness });
    if ("error" in ok) {
      console.error(ok.error);
      return 1;
    }
    await recordSkillUsage(name, "create", { home, createdBy: "human" });
    console.log(ok.path);
    return 0;
  }
  if (sub === "unlink") {
    const { removed, kept } = await unlinkHarnessSkills({ home });
    console.log(`unlinked ${removed.length} harness symlink(s); kept ${kept.length} pinned`);
    for (const r of removed) console.log(`  - ${r}`);
    return 0;
  }
  if (sub === "archive") {
    const { archived, kept } = await archiveAutoGeneratedSkills({ home });
    console.log(`archived ${archived.length} auto-generated skill(s) into skills/.archive; kept ${kept.join(", ") || "(none)"}`);
    for (const a of archived) console.log(`  - ${a}`);
    return 0;
  }
  if (sub === "pin" || sub === "unpin") {
    const name = args[1];
    if (!name) {
      console.error(SKILL_USAGE);
      return 2;
    }
    if (sub === "pin") {
      // Pinning is bookkeeping, not a prompt load: warn, do not refuse.
      const warn = await skillBodyProblem(name, home);
      if (warn) console.error(`agentik skills pin: warning — ${name}: ${warn} (link will be refused)`);
    }
    const pinned = await pinSkill(name, { home, unpin: sub === "unpin" });
    console.log(`pinned: ${pinned.join(", ") || "(none)"}`);
    return 0;
  }
  if (sub === "link") {
    const name = args[1];
    if (!name) {
      console.error(SKILL_USAGE);
      return 2;
    }
    const dir = join(memoryPaths(agentikHome(home)).skills, name);
    let linked: string[];
    try {
      linked = await linkHarnessSkill(name, dir);
    } catch (err) {
      console.error(`agentik skills link: ${err instanceof Error ? err.message : String(err)}`);
      return 1;
    }
    console.log(`linked ${name} into ${linked.length} harness home(s)`);
    return 0;
  }
  if (sub === "update") {
    const name = args[1];
    const rest = args.slice(2);
    const parsed = parseRun(rest);
    const updateGoal = parsed.goal;
    if (!name || !updateGoal) {
      console.error("usage: agentik skill update <name> <goal>");
      return 2;
    }
    const ok = await updateSkill(
      name,
      { goal: updateGoal, steps: [`Updated from CLI: ${updateGoal}`] },
      { home: parsed.flags.agentikHome ? homeFor(parsed.flags) : home },
    );
    if ("error" in ok) {
      console.error(ok.error);
      return 1;
    }
    await recordSkillUsage(name, "patch", { home: parsed.flags.agentikHome ? homeFor(parsed.flags) : home });
    console.log(ok.path);
    return 0;
  }
  console.error(SKILL_USAGE);
  return 2;
}

/** Wall-clock bound for one `agentik spawn`. 0 (via --timeout 0) means unbounded. */
export const DEFAULT_SPAWN_TIMEOUT_S = 1800;

function str(v: string | boolean | undefined): string | undefined {
  return typeof v === "string" ? v : undefined;
}

if (import.meta.main) {
  main().then(
    (code) => process.exit(code),
    (err) => {
      console.error(err);
      process.exit(1);
    },
  );
}
